# Stage 1: deps
FROM maven:3.9.6-eclipse-temurin-17 AS deps
WORKDIR /app

# copy only pom.xml (so cache is preserved)
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Stage 2: build
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
COPY --from=deps /root/.m2 /root/.m2
RUN mvn clean package -DskipTests

# Stage 3: runtime
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
